spring.application.name=sample
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=My Basic app
info.app.description=A Basic Funny Application
info.app.version=1.0.0

spring.security.user.name=admin
spring.security.user.password=Admin@123